---
baseURL: "https://indieweb.nyc/"
buildFuture: true
disableHugoGeneratorInject: true
disableKinds:
- RSS
- sitemap
- taxonomy
- taxonomyTerm
languageCode: "en-us"
params:
  ISO8601: "2006-01-02T15:04:05-0700"
  humanDate: "January 2, 2006 3PM"
permalinks:
  events: /:year/:month/:day/:slug/
title: "IndieWeb Events in New York City"
